### ISSUE TITLE
Nametag getting used during cooldown

### ISSUE THREAD

**Issue by RebelMythik** [RebelMythik/AntiVillagerLag#14]
**Describe the bug**
Nametag getting used during cooldown
**Server Info**
Server Version (Ex. 1.18.2):
1.18.2

Type of Server Software (Ex. Paper): 
**To Reproduce**
1. Name villager once
2. Name a second time a cooldown and nametag gets used

**Expected behavior**
Nametag not being used
**Screenshots**

**Additional context**

**Comment by D-VR** [comment]
question is, does this always happen or only from time to time? :thinking: 

event listeners are not defined in a special order, there may be undefined behaviour due to cancelled events
maybe be better to try and track the issue down once it's deterministic
