### ISSUE TITLE
Renaming Not Working Properly

### ISSUE THREAD

**Issue by RebelMythik** [RebelMythik/AntiVillagerLag#25]
Ai Not toggling properly.

most likely due to AVL tag

**Comment by D-VR** [comment]
legacy issue, plugin thinks old disabled villagers are NPCs (due to missing AVL flag)
fix would be a config option to disable check

a better fix would be checking if the villager should be disabled and set the marker (but need to make sure config is honoured)

**Comment by D-VR** [comment]
workaround is to downgrade to prior used AVL version, enable/ de-optimize all villagers, upgrade, and then optimize villagers again

(or using the /data command to manually enable AI of villagers)

**Comment by D-VR** [comment]
there is also a beta build on discord which fixes the issue

**Comment by D-VR** [comment]
this has not been pushed into the main build, I'd add it as a PR in the next few days since i have time then
