### ISSUE TITLE
villagers move through water

### ISSUE THREAD

**Issue by SrMonsterYT** [RebelMythik/AntiVillagerLag#31]
**Server Info**
Server Version 1.19.2 paper 

allow the villager to be pushed by water and players, this would be very useful if players want to move the villager

**Comment by SrMonsterYT** [comment]
asks me to open a report and doesn't even answer me.

**Comment by RebelMythik** [comment]
> asks me to open a report and doesn't even answer me.

I asked you to open this so its here while i look into adding the feature. I've been trying to find a way to actually implement this feature without the use of NMS

**Comment by D-VR** [comment]
> asks me to open a report and doesn't even answer me.

you are always free to make your own PR to add a feature you want.

I would say this feature is not possible without doing it in a hacky way (which is hard to maintain especially for such a niche feature)

have you tried placing villagers in boats if you *need* them to be pushable by water?

this plug-in also aims to reduce the effect of trading halls... which don't have villagers being pushed by water anyways. 

if you need to move villagers temporarily you use can minecarts or boats and you can always just re-enable their ai to do so.

**Comment by RebelMythik** [comment]
I believe I have a way of doing it and will try. Will not be released in the next update though.

**Comment by RebelMythik** [comment]
Completed
