### ISSUE TITLE
Disable sleeping

### ISSUE THREAD

**Issue by Shybella** [RebelMythik/AntiVillagerLag#32]
**Is your feature request related to a problem? Please describe.**

When players have villagers in pens if there is any kind of difficulty in pathfinding to a bed it causes high tick times. This is with 4 villagers.

https://prnt.sc/15SMRpBYto6F

**Describe the solution you'd like**

Disable villager sleeping.

**Comment by RebelMythik** [comment]
Naming the villagers will disable sleeping.
