### ISSUE TITLE
Cannot un optimize after converting to zombie

### ISSUE THREAD

**Issue by MrEDok** [RebelMythik/AntiVillagerLag#35]
**Describe the bug**
When converting a (NoAI, Optimize) villager to a zombie and cure the villager Their (NoAI, Optimize) tag still exist but when using a name tag to rename them they doesn't turn back to normal

**Server Info**
Server Version: 1.19.2

Type of Server Software (Ex. Paper): Purpur (b1819)
**To Reproduce**
1. Get villager a job
2. Nametag (Optimize)
3. Convert the villager to a zombie villager and cure it
4. Trading with them will be fine.
5. name tag them with something else
6. Their doesn't convert back to normal villager (WithAI)

**Expected behavior**
They regain their AI when nametag after converting back from zombie villager

**Screenshots**

**Additional context**

**Comment by MrEDok** [comment]
it appeared that
before zombified
`"BukkitValues":{
   "antivillagerlag:cooldown":1666109921L,
   "antivillagerlag:disabledbyblock":"false",
   "antivillagerlag:time":1632483868L,
   "antivillagerlag:levelcooldown":1666109282L,
   "antivillagerlag:marker":"AVL"
}`

after zombified and cured
`"BukkitValues":{
   "antivillagerlag:cooldown":1666109921L,
   "antivillagerlag:disabledbyblock":"false",
   "antivillagerlag:time":1632483868L,
   "antivillagerlag:levelcooldown":1666109282L
}`
marker is gone.

and no matter how many time the villager get nametag optimize, unoptimize it never get their AI back

**Comment by RebelMythik** [comment]
Fixed in the most recent update
