### ISSUE TITLE
Moving villagers too far from origin restores vanilla behavior 

### ISSUE THREAD

**Issue by Syntaxvgm** [RebelMythik/AntiVillagerLag#36]
**Is your feature request related to a problem? Please describe.**
On our vanilla server, one of the complaints I've encountered when brining up this plugin is that players will be able to lobotomize villagers and use this to easily move them in their dumb state, which of course is not vanilla. 

**Describe the solution you'd like**
I would like a configurable distance, where the origin point of a lobotomized villager is saved, and if it has deviated from that origin point by the distance configured it strips the nametag and reverts it to a vanilla villager with AI. 

**Additional context**
Requiring standing on a certain block is an option, but not an ideal one as we're looking for easy conversion of existing halls and to make it easy for new players to come back and optimize later if they didn't know about it when they made their halls. We don't want to enforce use of this plugin, but encourage it and allow people who do use it to have halls that bypass our villager limit rules.

**Comment by RebelMythik** [comment]
After looking into this not really viable.
