### ISSUE TITLE
Emerald block doesn't optimize villagers

### ISSUE THREAD

**Issue by mattcloward** [RebelMythik/AntiVillagerLag#37]
**Describe the bug**

**Server Info**
Server Version: 1.19
Type of Server Software: Paper

**To Reproduce**
1. I added the plugin to my server.
2. I updated the config, setting "userenaming" and "useblocks" to true.
3. I started the server.
4. I put an emerald block under several villagers.
5. The villagers continued to look around and interact with their blocks of interest.
6. I can tell the plugin is loaded correctly because "/avlreload 50" renames all the villagers within a certain radius with the name I specified in the config "stillager."

**Expected behavior**
I expect both changing the villagers names and changing what block is under them to change them to no AI.

**Additional context**
Here is my current config file:

```# What the villager needs to be named to be disabled.
NameThatDisables: stillager

# This needs to be a valid block ID to work.
BlockThatDisables: EMERALD_BLOCK

# Please do the time in ticks or it will break the plugin. There is 24,000 ticks in a single day.
# See https://minecraft.fandom.com/wiki/Daylight_cycle for more info
RestockTimes:
  time1: 1000
  time2: 5000
  time3: 9000
  time4: 13000

# This time is in seconds. This cooldown for renaming is to prevent possible abuse
# of people repeatedly disabling ai and re-enabling it to get double trades. I would keep this
# at the minimum time of 10 minutes or 600 seconds due anything less allowing for the double trades to happen.
cooldown: 600

# The maximum radius in blocks the /avloptimize command can search
RadiusLimit: 50

toggleableoptions:
  # If set to true, nametags will be used instead of being infinite.
  usenametags: false
  
  # One of these following options needs to be true for the plugin to work.
  # This will allow nametags to disable and renable the Villager AI.
  userenaming: true
  
  # This will allow a block to disable and renable the Villager AI.
  useblocks: true

messages:
  no-permission: '&cYou don''t have permission to use this command.'
  reload-message: '&aPlugin successfully reloaded.'
  cooldown-message: '&cYou can rename the villager again in %avlminutes% minutes and
    %avlseconds% seconds.'
  cooldown-block-message: '&cYou can toggle this villager''s AI again in %avlminutes%
    minutes and %avlseconds% seconds.'
  cooldown-levelup-message: '&cThe villager is currently leveling up! You can use
    the villager again in %avlseconds% seconds.'
  next-restock: '&cThe next restock for the villager will be in %avlrestockmin% minutes
    and %avlrestocksec% seconds.'
  correct-usage: '&cCorrect Usage is /avloptimize <radius>'
  radius-limit: '&cThe radius you tried is to big. Radius limit is 50 blocks.'
```

**Comment by RebelMythik** [comment]
Sorry for the late reply but it seems to working fine for me on my test server. See if the plugin works by itself first.

**Comment by D-VR** [comment]
The problem is that blocks only disable after you have interacted with a Villager.

So you need to right click them atleast once while they stand on the block to enable/disable them.
This is a conscious design choice of the plug-in:

- for performance reasons (don't want to check every villager every x ticks!)
- because the main goal was to optimize villager trading halls, where you interact with the villagers daily
- we want to make sure the Player is allowed to interact with the villager, before messing with AI

If you use the nametag it would have worked, since you interact with the villager while renaming.

**Comment by mattcloward** [comment]
Sorry, just got back to this.
After removing a stillagers data pack we had which I thought was interacting poorly with this plugin, I tried interacting with the villagers after the emerald block is below them like you suggested and it still doesn't work. Changing their name also doesn't work. The only part of the plugin that appears to work is the avloptimize command, but then I can't revert the villager ai. Do you have any other ideas about what might be happening?

**Comment by RebelMythik** [comment]
Sorry for the late reply. Please deop yourself as the plugin as a permission that bypasses the plugin and doesn't optimize the villagers. If you have further issue please join the discord
