### ISSUE TITLE
Allow to add tags to villagers in addition to names 

### ISSUE THREAD

**Issue by jakedruth** [RebelMythik/AntiVillagerLag#39]
**Is your feature request related to a problem? Please describe.**
I'm not a huge fan of always seeing optimize, the default name, over every villager's head. It would be a nice feature if you could add a tag instead, and have the same effect as giving a villager a specific name. 

**Describe the solution you'd like**
Adding Tags to villagers is a little tedious, but via commands you can call /tag @e[type=villager] add noAI

**Comment by RebelMythik** [comment]
If you don't want to see the tags above their heads I recommend using the block feature of the plugin.
