### ISSUE TITLE
Disabling the ability to bargain for villagers with AI

### ISSUE THREAD

**Issue by hilltty** [RebelMythik/AntiVillagerLag#41]
**Is your feature request related to a problem? Please describe.**
Players often do not want to lose their comfort for the sake of server performance, so let's make them

**Describe the solution you'd like**
Prevent trading with villagers without disabling AI for them

**Comment by D-VR** [comment]
~~This is not in scope for the plug-in.~~

~~Use other plugins like https://www.spigotmc.org/resources/disable-villager-trade.96716/ if you only want this feature.~~

reading through discord I now understand the Idea, it's pretty good!

(only disable trading for villagers which haven't been optimized)

https://github.com/dodoflix/DisableVillagerTrade can be used as a reference

**Comment by RebelMythik** [comment]
Completed
