### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by folkhack** [RebelMythik/AntiVillagerLag#44]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Numerous server plugin projects are starting to support Folia, as its growing popularity and performance-centric nature are intriguing to many operators. These operators are interested in migrating to Folia to enhance metrics like MSPT, TPS, and the overall player experience.

AntiVillagerLag serves as a fundamental tool for operators tackling these very issues - MSPT, TPS, and the general player experience. I believe there is a significant opportunity for positive synergy if Folia and AntiVillagerLag are used in tandem.

The requested solution/feature is to add explicit Folia support to AntiVillagerLag.

**Comment by RebelMythik** [comment]
Hey sorry for the late reply I have been somewhat inactive recently. Have you been able to test the current plugin on folia at all? And if so can you send the error the plugin throws.

**Comment by NewPixelDev** [comment]
+1, please add support for Folia if you can Thanks

**Comment by RebelMythik** [comment]
Hey! I've decided not to add Folia support as doing so is pointless.

The main reasons being Folia will not suffer from the issue of Villagers and a smaller reason of it hasn't been released yet.
