### ISSUE TITLE
Work automatically without invoking command

### ISSUE THREAD

**Issue by Netherwhal** [RebelMythik/AntiVillagerLag#45]
It would be great if this plugin could work automatically with workstation + radius without a player having to invoke the command.

Meaning it will check if a villager is close to a workstation and then automatically optimize.

**Comment by RebelMythik** [comment]
Hey! Sorry for the late reply as I have been inactive. For this case I believe using blocks would be a better feature as workstations can cause farms to break on accident like Iron Golem Farms. If you would still be interested in this feature but with blocks let me know.

**Comment by Netherwhal** [comment]
How about workstation within 1-2 and basically trapped (I am not sure it is easy to detect if entity can not move?). Or maybe no bed close by? Maybe even if villager has been interacted with at least twice, brain goes dead? Would have to be stored somewhere to keep state across server restarts.

Problem with blocks: it requires players to distinctively do something, this is for an Anarchy server where I do not have control over what a player does.

**Comment by RebelMythik** [comment]
There is a current option in the plugin the requires villagers to be disabled to trade with them. That could force them to do the blocks. The blocks thing is possible but would hard to detect and the beds thing should be relatively simple hopefully.
