### ISSUE TITLE
1.20.2 Refill and Nametag problems

### ISSUE THREAD

**Issue by LeonMT1** [RebelMythik/AntiVillagerLag#47]
**Describe the bug**
The Villager dosent refill and the nametags disaper when you use them.

**Server Info**
Paper 1.20.2

Type of Server Software (Ex. Paper): 
Paper
**To Reproduce**
1. Place a Villager
2. Optimize them with a Nametag (the nametag disaper)
3. Trade the Villager to out off stock and he dosent refill

**Expected behavior**
1. The Nametag dosent disaper
2. The Villager refill

**Comment by RebelMythik** [comment]
Hey! Can you send your config as this is working fine when I test it on 1.20.2

**Comment by LeonMT1** [comment]
It was the Default i have deleted it sorry
