### ISSUE TITLE
After removing the plugin, villagers are not restocking

### ISSUE THREAD

**Issue by miguotw** [RebelMythik/AntiVillagerLag#49]
**Describe the bug**
When I remove the plugin and restart the server, villagers still appear to have their AI disabled and won't restock.

**Server Info**
Server Version (Ex. 1.18.2): 1.20.1

Type of Server Software (Ex. Paper): Purpur

**To Reproduce**
1. Remove AntiVillagerLag-2.3.1.jar from plugins.
2. Start server.
3. Players have reported that villagers are not restocking.

**Comment by RebelMythik** [comment]
Hey! Did you re-enable the villagers before removing the plugin?

**Comment by 0ZyroX** [comment]
how to re-enable villagers ?

> Hey! Did you re-enable the villagers before removing the plugin?

**Comment by RebelMythik** [comment]
> how to re-enable villagers ?
> 
> > Hey! Did you re-enable the villagers before removing the plugin?

Renaming them to something else will re-enable the villagers
