### ISSUE TITLE
Cooldown not working 1.20.4

### ISSUE THREAD

**Issue by agoniaprivat** [RebelMythik/AntiVillagerLag#50]
**Describe the bug**
Restocks don't work on server version 1.20.4, the timer/cooldown stays at max time. 

**Server Info**
Purpur 1.20.4

Type of Server Software (Ex. Paper): 
**To Reproduce**
Title says it all

**Expected behavior**
Restocking works.

**Screenshots**

**Additional context**

**Comment by pjindras** [comment]
I have the same problem, purpur 1.20.4.

**Comment by RebelMythik** [comment]
Could you send the output of /data get entity @e[type=minecraft:villager, sort=nearest, limit=1] 

next to broken villager (first few lines is enough)

**Comment by RebelMythik** [comment]
No response
