### ISSUE TITLE
Add option to config to allow villagers to roam while optimized

### ISSUE THREAD

**Issue by SfSuralias** [RebelMythik/AntiVillagerLag#51]
**Is your feature request related to a problem? Please describe.**

A lot of my players like to have villagers wandering their town, because it give a little bit of life and activity to their towns, but it lags the server very badly to have unoptimized villagers.

**Describe the solution you'd like**

I was wondering if you could add an option to the configuration that disables all of the worst issues of the villager AI, but allows them to still wander around. Have an option to turn this off in the config too, if it ends up being the straw that breaks the camel's back in that it still causes lag for the server, but then if it doesn't cause lag, it could be enabled on a case by case basis for each server and their owner and players to decide.

**Additional context**

Thanks for your work on this issue. The plugin has really resolved a lot of issues with lag for many servers. You're brilliant, and wonderful.

**Comment by RebelMythik** [comment]
Unfortunately this is not possible due to how the plugin works. It fully turns the brain / ai off of the villager
