### ISSUE TITLE
Villagers not un-optimizing on 1.20.4

### ISSUE THREAD

**Issue by satadrive420** [RebelMythik/AntiVillagerLag#52]
**Describe the bug**
Villagers aren't un-optimizing when you name them something else.
**Server Info**
Server Version (Ex. 1.18.2): 1.20.4

Type of Server Software (Ex. Paper): 
**To Reproduce**
1. Optimize a villager (we use the nametag method)
2. Un-optimize a villager
3. Attempt to infect villager with a zombie

**Expected behavior**
Villager should regain its normal AI, including the ability to be re-infected.

**Screenshots**

**Additional context**

**Comment by PiporGames** [comment]
I just did this and now all my villagers on my server are perma frozen... I need help ASAP

**Comment by RebelMythik** [comment]
Not a bug. Remove the avl.disable permission from yourself.
